export const mockData = [
  { id: 1, label: 'New York' },
  { id: 2, label: 'Los Angeles' },
  { id: 3, label: 'Chicago' },
  { id: 4, label: 'Houston' },
  { id: 5, label: 'Phoenix' },
  { id: 6, label: 'Philadelphia' },
  { id: 7, label: 'San Antonio' },
  { id: 8, label: 'San Diego' },
  { id: 9, label: 'Dallas' },
  { id: 10, label: 'San Jose' },
  { id: 11, label: 'Austin' },
  { id: 12, label: 'Jacksonville' },
  { id: 13, label: 'Indianapolis' },
  { id: 14, label: 'San Francisco' },
  { id: 15, label: 'Columbus' },
  { id: 16, label: 'Fort Worth' },
  { id: 17, label: 'Charlotte' },
  { id: 18, label: 'Detroit' },
  { id: 19, label: 'El Paso' },
  { id: 20, label: 'Memphis' },
  { id: 21, label: 'Boston' },
  { id: 22, label: 'Seattle' },
  { id: 23, label: 'Denver' },
  { id: 24, label: 'Washington' },
  { id: 25, label: 'Nashville' },
  { id: 26, label: 'Baltimore' },
  { id: 27, label: 'Louisville' },
  { id: 28, label: 'Milwaukee' },
  { id: 29, label: 'Portland' },
  { id: 30, label: 'Oklahoma City' },
  { id: 31, label: 'Las Vegas' },
  { id: 32, label: 'Albuquerque' },
  { id: 33, label: 'Tucson' },
  { id: 34, label: 'Fresno' },
  { id: 35, label: 'Sacramento' },
  { id: 36, label: 'Long Beach' },
  { id: 37, label: 'Kansas City' },
  { id: 38, label: 'Mesa' },
  { id: 39, label: 'Atlanta' },
  { id: 40, label: 'Colorado Springs' },
  { id: 41, label: 'Virginia Beach' },
  { id: 42, label: 'Omaha' },
  { id: 43, label: 'Raleigh' },
  { id: 44, label: 'Miami' },
  { id: 45, label: 'Oakland' },
  { id: 46, label: 'Minneapolis' },
  { id: 47, label: 'Tulsa' },
  { id: 48, label: 'Cleveland' },
  { id: 49, label: 'Wichita' },
  { id: 50, label: 'Arlington' },
  { id: 51, label: 'New Orleans' },
  { id: 52, label: 'Bakersfield' },
  { id: 53, label: 'Tampa' },
  { id: 54, label: 'Honolulu' },
  { id: 55, label: 'Aurora' },
  { id: 56, label: 'Anaheim' },
  { id: 57, label: 'Santa Ana' },
  { id: 58, label: 'St. Louis' },
  { id: 59, label: 'Riverside' },
]
